src/frontend/routes.py
"""ルーティング設定."""

from flask import Flask
from views.login import login_bp
from views.top import top_bp
from views.users import users_bp


def init_blueprint(app: Flask):
    """Blueprintを登録する."""
    app.register_blueprint(login_bp)
    app.register_blueprint(top_bp)
    app.register_blueprint(users_bp)

src/frontend/views/__init__.py
"""viewsパッケージ."""

src/frontend/views/login.py
"""ログイン画面のビュー."""

import requests
from flask import (
    Blueprint,
    current_app,
    flash,
    get_flashed_messages,
    redirect,
    render_template,
    request,
    session,
    url_for,
)


login_bp = Blueprint("login", __name__, url_prefix="/login")


@login_bp.route("", methods=["GET"])
def login_form():
    """ログイン画面を表示する."""
    # ログイン処理時の flash メッセージを取得
    error = get_flashed_messages(category_filter=["error"])
    if isinstance(error, list) and len(error) > 0:
        error = error[0]  # type: ignore
    return render_template("login.jinja", error=error)


@login_bp.route("", methods=["POST"])
def login():
    """ログイン処理を行う."""
    request_data = {"login_id": request.form.get("login_id"), "ignition_key": request.form.get("ignition_key")}
    current_app.logger.info(f"ACCESS: {current_app.config['BACKEND_URL'] + '/login'} DATA: {request_data}")
    data = requests.post(current_app.config["BACKEND_URL"] + "/login", json=request_data)
    current_app.logger.info(f"RESPONSE: {data.status_code} {data.json()}")
    if data.status_code == 200:
        session["login_user"] = data.json()["user_id"]
        return redirect(url_for("top.home"))
    else:
        flash("ログインIDまたはパスワードが間違っています。", "error")
        return redirect(url_for("login.login_form"))

src/frontend/views/top.py
"""トップ画面のビュー."""

from flask import Blueprint, render_template, session
from utils import get_common_data


top_bp = Blueprint("top", __name__, url_prefix="/")


@top_bp.route("")
def home():
    """トップ画面を表示する."""
    common_data = get_common_data()
    # たぶんセッションクッキーがちゃんと設定されているか見るためのテスト用に書いた気がする
    session["login_user"] = "fuga"
    return render_template("index.jinja", **common_data)

src/frontend/views/users.py
"""ユーザ画面のビュー."""

import time

import requests
from flask import Blueprint, Response, current_app, jsonify, render_template, request
from utils import get_common_data


users_bp = Blueprint("users", __name__, url_prefix="/users")


@users_bp.route("/list")
def home():
    """ユーザ画面を表示する."""
    common_data = get_common_data()
    return render_template("users/list.jinja", **common_data)


@users_bp.route("/api/list", methods=["POST"])
def api_list() -> Response:
    """ユーザの一覧を json 形式で返す.

    Returns:
        Response: Flask の Response オブジェクト
    """
    json_data = request.get_json(silent=True)
    # 早すぎて動作確認できないので sleep を入れる
    time.sleep(0.5)
    data = requests.get(current_app.config["BACKEND_URL"] + "/users", params=json_data).json()

    return jsonify(data)


@users_bp.route("/api/modal/showable/<user_id>", methods=["POST"])
def api_list_user_id(user_id: str) -> Response:
    """モーダル画面に表示するための情報を返す.

    面倒なのでハードコードする.
    user_id を指定しているけど、まだ使う予定はない.

    Args:
        user_id (str): ログインユーザID

    Returns:
        Response: Flask の Response オブジェクト
    """
    current_app.logger.info(f"user_id: {user_id}")
    # 検索時に target に対応するデータを埋め込んでいて、それを label ごとにモーダル画面で読み込んでるだけ
    settings = [
        {"target": "user_id", "label": "社員ID"},
        {"target": "user_name", "label": "社員名"},
        {"target": "user_name_kana", "label": "社員名かな"},
        {"target": "email", "label": "email"},
        {"target": "gender", "label": "性別"},
        {"target": "age", "label": "年齢"},
        {"target": "birth_day", "label": "生年月日"},
        {"target": "blood_type", "label": "血液型"},
        {"target": "prefecture", "label": "都道府県"},
        {"target": "curry", "label": "カレーの食べ方"},
    ]
    return jsonify(settings)

src/frontend/templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <title>Document</title>
</head>
<body>
  <h1>Hello, Flask!</h1>
</body>
</html>

src/frontend/templates/components/modalComp.jinja
<div class="modal fade" id="modal" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">${ focus_item.user_id }</h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <table class="table  table-sm align-middle">
          <tr v-for="(value, key) in focus_item" :key="key">
            <th>${ key }</th>
            <td>${ value }</td>
          </tr>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

src/frontend/templates/components/toastComp.jinja
<!-- Flexbox container for aligning the toasts -->
<div aria-live="polite" aria-atomic="true" class="d-flex justify-content-center align-items-center">

  <!-- Then put toasts within -->
  <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
      {# <img src="..." class="rounded me-2" alt="..."> #}
      <strong class="me-auto">Bootstrap</strong>
      <small>11 mins ago</small>
      <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body">
      Hello, world! This is a toast message.
    </div>
  </div>
</div>

src/frontend/templates/components/userListModalComp.jinja
<div class="modal fade" id="modal" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">${ focus_item.user_id }</h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <table class="table  table-sm align-middle">
          <tr v-for="setting in modal_settings" :key="setting.target">
            <th>${ setting.label }</th>
            <td>${ focus_item[setting.target] }</td>
          </tr>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

src/frontend/templates/index.jinja
{% extends "layout/base.jinja" %}

{% block title %}トップ{% endblock %}

{% block content %}
<div class="container">
  <h1>トップページ</h1>
  <p>ここにページ固有の内容を記述します。</p>
  <p>タブのサンプル</p>
  <div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true">Home</button>
        </li>
        <li class="nav-item">
          <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false">Profile</button>
        </li>
        <li class="nav-item">
          <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact-tab-pane" type="button" role="tab" aria-controls="contact-tab-pane" aria-selected="false">Contact</button>
        </li>
      </ul>
    </div>
    <div class="card-body">
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0">これはHomeです</div>
        <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">これはProfileです</div>
        <div class="tab-pane fade" id="contact-tab-pane" role="tabpanel" aria-labelledby="contact-tab" tabindex="0">これはContactです</div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

src/frontend/templates/layout/base.jinja
<!DOCTYPE html>
<html data-bs-theme="auto">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&family=Nunito+Sans:ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{{ url_for_with_mtime('assets/bootstrap/css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for_with_mtime('assets/css/app.css') }}">
  <!-- Bootstrap Icons -->
  <link rel="stylesheet" href="{{ url_for('static', filename='assets/bootstrap/icons/font/bootstrap-icons.min.css') }}">
  <script src="{{ url_for_with_mtime('assets/js/color-modes.js') }}"></script>
  <script defer src="{{ url_for_with_mtime('assets/vue.global.prod.js') }}"></script>
  <!-- Bootstrap JS (Popper.js も含まれると思う) -->
  <script defer src="{{ url_for_with_mtime('assets/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  <!-- Axios -->
  <script defer src="{{ url_for_with_mtime('assets/axios.min.js') }}"></script>
  <title>{% block title %}{% endblock %}｜Flaskアプリのサンプル</title>
  <script defer src="{{ url_for_with_mtime('assets/js/card-collapse.js') }}"></script>
  {% block scripts %}{% endblock %}
</head>

<body>
  {% include 'layout/header.jinja' %}
  <div class="nav-space"></div>
  {% block content %}
  <h1>Hello, Flask!</h1>
  {% endblock %}
  {% include 'layout/footer.jinja' %}
  {% block bodyscripts %}
  <script></script>
  {% endblock %}
</body>

</html>

src/frontend/templates/layout/footer.jinja
<footer class="text-center">&copy; 2024 - {{ now.year }} landwarrior</footer>

src/frontend/templates/layout/header.jinja
<header>
  <nav class="navbar navbar-expand-lg fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">
        <img src="{{ url_for('static', filename='assets/yu_mark.svg') }}" alt="Logo" width="30" id="logo_light" class="d-inline-block align-text-top">
        <img src="{{ url_for('static', filename='assets/yu_mark_hanten.svg') }}" alt="Logo" width="30" id="logo_dark" class="d-none align-text-top">
        Flaskアプリのサンプル
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#menuNav" aria-controls="menuNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-between" id="menuNav">
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <button class="btn btn-link nav-link px-lg-2 dropdown-toggle d-flex align-items-center" type="button" aria-expanded="false" data-bs-toggle="dropdown" data-bs-display="static">
              人事
            </button>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/users/list"><i class="bi bi-people-fill"></i> 社員情報一覧</a></li>
              <li><a class="dropdown-item" href="/users/regist"><i class="bi bi-person-fill-add"></i> 社員情報登録</a></li>
              <li><a class="dropdown-item" href="/users/edit"><i class="bi bi-person-fill-lock"></i> あとなんか</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <button class="btn btn-link nav-link px-lg-2 dropdown-toggle d-flex align-items-center" type="button" aria-expanded="false" data-bs-toggle="dropdown" data-bs-display="static">
              社内申請
            </button>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#"><i class="bi bi-card-list"></i> 社内申請一覧</a></li>
              <li><a class="dropdown-item" href="#"><i class="bi bi-file-spreadsheet"></i> 経費精算申請</a></li>
              <li><a class="dropdown-item" href="#"><i class="bi bi-train-front"></i> 交通費精算申請</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">メニューほげ</a>
          </li>
        </ul>
        <hr class="d-lg-none">
        <ul class="dropdown d-flex navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="#">部署とか</a>
          </li>
          <li class="nav-item">
            <div class="vr d-none d-lg-flex h-100 mx-lg-2"></div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">ユーザー名とか</a>
          </li>
          <li class="nav-item">
            <div class="vr d-none d-lg-flex h-100 mx-lg-2"></div>
            <hr class="d-lg-none">
          </li>
          <li class="nav-item dropdown">
            {# ここの部分は color-modes.js とセットになっている #}
            <button class="btn btn-link nav-link px-lg-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button" aria-expanded="false" data-bs-toggle="dropdown" data-bs-display="static" aria-label="Toggle theme (auto)">
              <i id="current-theme" class="bi bi-circle-half"></i>
              <span class="d-lg-none ms-2" id="bd-theme-text">Toggle theme</span>
            </button>
            <ul class="dropdown-menu dropdown-menu-end" id="theme-switch" aria-labelledby="bd-theme-text">
              <li>
                <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="auto" aria-pressed="false">
                  <i class="bi bi-circle-half"></i> Auto
                </button>
              </li>
              <li>
                <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
                  <i class="bi bi-brightness-high-fill"></i> Light
                </button>
              </li>
              <li>
                <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
                  <i class="bi bi-moon-stars-fill"></i> Dark
                </button>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

src/frontend/templates/login.jinja
<!DOCTYPE html>
<html data-bs-theme="auto">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&family=Nunito+Sans:ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{{ url_for_with_mtime('assets/bootstrap/css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for_with_mtime('assets/css/app.css') }}">
  <!-- Bootstrap Icons -->
  <link rel="stylesheet" href="{{ url_for('static', filename='assets/bootstrap/icons/font/bootstrap-icons.min.css') }}">
  <script src="{{ url_for_with_mtime('assets/js/color-modes.js') }}"></script>
  <!-- Bootstrap JS (Popper.js も含まれると思う) -->
  <script defer src="{{ url_for_with_mtime('assets/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  <title>ログイン｜Flaskアプリのサンプル</title>
  <script defer src="{{ url_for_with_mtime('assets/js/login.js') }}"></script>
</head>

<body>
  <div class="login-container">
    <div class="container">
      <div class="card">
        <div class="card-body">
          <div class="row align-items-center">
            <div class="col-3">
              <img src="{{ url_for('static', filename='assets/yu_mark.svg') }}" alt="Logo" width="100%" id="logo_light" class="d-inline-block align-text-top">
              <img src="{{ url_for('static', filename='assets/yu_mark_hanten.svg') }}" alt="Logo" width="100%" id="logo_dark" class="d-none align-text-top">
            </div>
            <div class="col-9">
              <h1>Flaskアプリのサンプル</h1>
              <form action="{{ url_for('login.login') }}" method="post" id="login-form">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <input type="text" name="login_id" class="form-control" placeholder="ログインID">
                <input type="password" name="ignition_key" class="form-control" placeholder="パスワード">
                {% if error %}
                <div class="alert alert-danger pt-3" role="alert">
                  <i class="bi bi-exclamation-triangle"></i> {{ error }}
                </div>
                {% endif %}
                <div class="pt-3 text-center">
                  <button type="submit" class="btn btn-primary"><i class="bi bi-door-open"></i> ログイン</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="card-footer">
          <p class="text-center">&copy; 2024 Flaskアプリのサンプル</p>
        </div>
      </div>
    </div>
  </div>
</body>

</html>

src/frontend/templates/users/list.jinja
{% extends "layout/base.jinja" %}

{% block title %}社員情報一覧{% endblock %}

{% block scripts %}
<link rel="stylesheet" href="{{ url_for_with_mtime('assets/flatpickr/flatpickr.min.css') }}">
<script defer src="{{ url_for_with_mtime('assets/flatpickr/flatpickr.min.js') }}"></script>
<script defer src="{{ url_for_with_mtime('assets/flatpickr/l10n/ja.js') }}"></script>
<script defer src="{{ url_for_with_mtime('assets/js/alertShow.js') }}"></script>
<script defer src="{{ url_for_with_mtime('assets/js/list.js') }}"></script>
{% endblock %}

{% block content %}
<div class="container-fluid" id="user_list" v-cloak>
  <h1 class="text-center">社員情報一覧</h1>
  <div class="container">
    <div class="card">
      <div class="card-header d-flex justify-content-between align-items-center">
        <div class="lead"><i class="bi bi-search"></i> 検索</div>
        <button class="btn btn-sm collapse-toggle" type="button" data-bs-toggle="collapse" data-bs-target="#search_body" aria-expanded="false" aria-controls="search_body">
          <i class="bi bi-dash"></i>
        </button>
      </div>
      <form id="search_body" class="collapse show">
        <div class="card-body">
          <div class="row gy-3">
            <div class="col-lg-4 col-md-6" v-for="item in search_items" :key="item.id">
              <div class="input-group" v-if="item.type == 'text'">
                <div class="form-floating">
                  <input type="text" class="form-control" :id="item.id" :placeholder="item.label" v-model="item.value">
                  <label :for="item.id">${ item.label }</label>
                </div>
                <button class="btn btn-outline-inputgroup" type="button" title="clear" @click="clearInputValue($event.target)"><i class="bi bi-x-lg"></i></button>
              </div>
              <div class="input-group flatpickr" v-if="item.type == 'date'">
                <div class="form-floating">
                  <input type="text" class="form-control" :id="item.id" :placeholder="item.label" v-model="item.value" maxlength="10">
                  <label :for="item.id">${ item.label }</label>
                </div>
                <button class="btn btn-outline-inputgroup" type="button" title="clear" data-clear><i class="bi bi-x-lg"></i></button>
              </div>
            </div>
          </div>
        </div>
        <div class="card-footer">
          {# こっちはスピナーを表示してボタンは非活性 #}
          <button class="btn btn-outline-search" type="button" disabled v-if="searching">
            <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
            検索
          </button>
          {# こっちは機能する検索ボタン #}
          <button type="button" class="btn btn-outline-search" @click="search" v-else>
            <i class="bi bi-search"></i> 検索
          </button>
        </div>
      </form>
    </div>
  </div>
  {# トーストが思ってた挙動とは違ったので、アラートを試してみる #}
  <div id="alert-area"></div>

  <div class="card">
    <div class="card-header">
      <div class="lead"><i class="bi bi-list"></i> 検索結果一覧</div>
    </div>
    <div class="card-body">
      <nav aria-label="Page navigation example" v-if="result_items.length > 0">
        <ul class="pagination">
          <li class="page-item">
            <a class="page-link" href="#" aria-label="Previous" @click.prevent="backPage">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
          <li class="page-item" :class="page == currentPage ? 'active' : ''" v-for="page in maxPage">
            <a class="page-link" @click.prevent="changePage(page)" v-if="page != currentPage" href="#">${ page }</a>
            <span class="page-link" v-if="page == currentPage">${ page }</span>
          </li>
          <li class="page-item">
            <a class="page-link" href="#" aria-label="Next" @click.prevent="nextPage">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        </ul>
      </nav>
      <div class="table-responsive">
        <table class="table table-sm table-hover align-middle">
          <thead>
            <tr>
              <th style="width: 170px">社員ID</th>
              <th style="width: 140px">社員名</th>
              <th class="d-none d-lg-table-cell">社員名カナ</th>
              <th class="d-none d-md-table-cell">email</th>
              <th class="d-none d-xl-table-cell">性別</th>
              <th class="d-none d-md-table-cell">年齢</th>
              <th class="d-none d-lg-table-cell">血液型</th>
              <th>都道府県</th>
              <th class="d-none d-xl-table-cell">カレーの食べ方</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="item in paginatedResultItems" @click="showModal(item.user_id)">
              <td class="text-truncate">${ item.user_id }</td>
              <td class="text-truncate">${ item.user_name }</td>
              <td class="d-none d-lg-table-cell text-truncate">${ item.user_name_kana }</td>
              <td class="d-none d-md-table-cell text-truncate">${ item.email }</td>
              <td class="d-none d-xl-table-cell">${ item.gender }</td>
              <td class="d-none d-md-table-cell">${ item.age }</td>
              <td class="d-none d-lg-table-cell">${ item.blood_type }</td>
              <td>${ item.prefecture }</td>
              <td class="d-none d-xl-table-cell text-truncate">${ item.curry }</td>
            </tr>
          </tbody>
        </table>
      </div>
      <nav aria-label="Page navigation example" v-if="result_items.length > 0">
        <ul class="pagination">
          <li class="page-item">
            <a class="page-link" href="#" aria-label="Previous" @click.prevent="backPage">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
          <li class="page-item" :class="page == currentPage ? 'active' : ''" v-for="page in maxPage">
            <a class="page-link" @click.prevent="changePage(page)" v-if="page != currentPage" href="#">${ page }</a>
            <span class="page-link" v-if="page == currentPage">${ page }</span>
          </li>
          <li class="page-item">
            <a class="page-link" href="#" aria-label="Next" @click.prevent="nextPage">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
  <div class="row">
    <div class="col-3 text-center">
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal">js なしでモーダルを表示するボタン</button>
    </div>
    <div class="col-3 text-center">
      <button type="button" class="btn btn-outline-primary" @click="showToast">show toast</button>
    </div>
    <div class="col-3 text-center">
      <button type="button" class="btn btn-outline-danger" @click="showAlert">アラートを表示させてみるボタン</button>
    </div>
    <div class="col-3 text-center">
      <button type="button" class="btn btn-outline-primary" @click="showAlert2">アラートを表示させてみるボタン</button>
    </div>
    <div class="col-3 text-center">
      <button type="button" class="btn btn-outline-secondary" @click="showAlert3">アラートを表示させてみるボタン</button>
    </div>
    <div class="col-3 text-center">
      <button type="button" class="btn btn-outline-info" @click="showAlert4">アラートを表示させてみるボタン</button>
    </div>
    <div class="col-3 text-center">
      <button type="button" class="btn btn-outline-success" @click="showAlert5">アラートを表示させてみるボタン</button>
    </div>
    <div class="col-3 text-center">
      <button type="button" class="btn btn-outline-warning" @click="showAlert6">アラートを表示させてみるボタン</button>
    </div>
  </div>
  {% include 'components/userListModalComp.jinja' %}
  {# トーストは思ってた挙動と違った #}
  {% include 'components/toastComp.jinja' %}
</div>
{% endblock %}

{% block bodyscripts %}
<script>
  document.addEventListener('DOMContentLoaded', () => {
    axios.defaults.headers.common["X-CSRFToken"] = "{{ csrf_token() }}";
  });
</script>
{% endblock %}

src/frontend/templates/users/main.jinja
{% extends "layout/base.jinja" %}

{% block title %}人事{% endblock %}

{% block content %}
<div class="container">
  <h1>社員情報一覧</h1>
  <p>ここにページ固有の内容を記述します。</p>
</div>

{% endblock %}